# When in TEST_MODE, no models will be loaded and only dummy data will be returned
TEST_MODE: False

# Change this to disable LLM for ablation study purpose
USE_LLM: True

DEFAULT_CAPTION_MODEL: blip-image-captioning-base

DEFAULT_LLM_MODEL: facebook/opt-125m

# Options：['test', 'musicgen-small', 'musicgen-medium', 'musicgen-large', 'suno']
DEFAULT_MUSIC_MODEL: musicgen-small


CAPTION_MODEL_CONFIG:
  VIDEO_SAMPLE_AMOUNT: 20

LLM_MODEL_CONFIG:
  # Platform type
  # Options：['xinference', 'ollama', 'oneapi', 'fastchat', 'openai', 'custom openai']
  # This option is not implemented yet ¯\_(シ)_/¯
  PLATFORM_TYPE: local

  # OpenAI API URL
  #API_BASE_URL: http://10.29.118.247:9997/v1
  API_BASE_URL: local

  # api key if available
  # Replace EMPTY with your OpenAI API key from https://platform.openai.com/account/api-keys
  API_KEY: EMPTY

  API_PROXY: ''

  API_CONCURRENCIES: 1

MUSIC_MODEL_CONFIG:
  API_BASE_URL: https://suno-api-psi-one.vercel.app/
